all:
  hosts:
    prodesk:
      ansible_host: "{{ lookup('env', 'PRODESK_HOST') }}"
      ansible_user: lazergreen
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
      ansible_python_interpreter: /usr/bin/python3.12
